# -------------------------------------------------------------------------
# DOCKER COMPOSE FILE for QUANTiCA Algorithmic Trading Platform
# -------------------------------------------------------------------------
# 
# http://getquantica.com
# 
# HOWTO
# Please find [YOUR_LOCAL_PATH] and replace it with your own local path.
#
# -------------------------------------------------------------------------

version: '2'

services:

# -------------------------------------------------------------------------
# NATS SERVER exposed ports 4222 (server) and 8222 (monitoring)
# -------------------------------------------------------------------------
  nats-server:
    image: nats:latest
    container_name: nats-srv
    hostname: nats-srv
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"

# -------------------------------------------------------------------------
# NATS BOARD listen on 4223   --- DEVELOP ONLY
# -------------------------------------------------------------------------
#  nats-board:
#    image: chrkaatz/natsboard
#    container_name: nats-board
#    hostname: nats-board
#    restart: unless-stopped
#    environment:
#      - NATS_MON_URL=http://nats-srv:8222
#    ports:
#      - "4223:3000"

# -------------------------------------------------------------------------
# DB PERSISTENCE LAYER - MARIADB SRV 
# -------------------------------------------------------------------------
  quantica-db:
    image: asfolcini/quantica-mariadb
    container_name: quantica-mariadb
    hostname: quantica-db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=quantica
      - PGID=1000
      - PUID=1000
#    volumes:
#      - c:/QT/QUANTiCA-workspace/DB:/var/lib/mysql
#      - c:/QT/QUANTiCA-workspace/DB/logs/:/var/log/mysql
    ports:
      - "3306:3306"
          
     
      
# -------------------------------------------------------------------------
# QUANTICA SERVER
# -------------------------------------------------------------------------
  quantica-srv:
    image: asfolcini/quantica
    container_name: quantica-srv
    hostname: quantica-srv
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
#      - [YOUR_LOCAL_PATH]:/config
      - c:/QT/QUANTiCA-workspace:/config
    ports:
      - "8081:8081"

# -------------------------------------------------------------------------
# QUANTICA WORKBENCH
# -------------------------------------------------------------------------
  quantica-workbench:
    image: asfolcini/quantica-workbench
    container_name: quantica-workbench
    hostname: quantica-workbench
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
# This path should be the same of one used in Quantica-server
#      - [YOUR_LOCAL_PATH]:/config    
      - c:/QT/QUANTiCA-workspace:/config
    ports:
      - "80:80"
      - "443:443"
      



# -------------------------------------------------------------------------
# NETWORKS LAYERS
# -------------------------------------------------------------------------      
  


